[project]
name = "socketio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "eventlet>=0.40.0",
    "python-socketio>=5.13.0",
    "uvicorn==0.34.2",
    "werkzeug==3.1.3",
]
